services:
  airflow:
    image: apache/airflow:2.10.5
    container_name: ecommerce-airflow
    command: standalone
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "pytest"
      DATABASE_URL: "postgresql+psycopg2://ecommerce_user:ecommerce_password@ecommerce-postgres:5432/ecommerce"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/project/src
      - ./sql:/opt/airflow/project/sql
      - ./tests:/opt/airflow/project/tests
      - airflow_data:/opt/airflow

volumes:
  airflow_data: