version: 2

models:
  - name: daily_revenue
    columns:
      - name: order_date
        tests:
          - not_null
          - unique
      - name: revenue
        tests:
          - not_null

  - name: category_revenue_en
    columns:
      - name: category
        tests:
          - not_null
          - unique
      - name: revenue
        tests:
          - not_null
  - name: delivery_performance
    columns:
      - name: month
        tests:
          - not_null
          - unique
      - name: avg_delivery_days
        tests:
          - not_null